---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/predreams/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R videos $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp readme.md $DEPLOYPATH